// Checks that code generated by `subxt-cli codegen` compiles. Allows inspection of compiler errors
/// directly, more accurately than via the macro and `cargo expand`.
///
/// Generate by:
///
/// - run `tidechain --dev --tmp` node locally
/// - cargo install --git https://github.com/tide-labs/substrate --branch=tidechain --force
/// - `subxt codegen | rustfmt --edition=2021 --emit=stdout > tidext/tests/integration/codegen/tidechain.rs`

#[rustfmt::skip]
#[allow(clippy::all)]
mod tidechain;
